services:
  mysqldb:
    image: mysql:9
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - ./resources/data:/var/lib/mysql-files/
    ports:
      - 3307:3306
